#pragma once
#import <Foundation/Foundation.h>
// GENERATED by scripts/provision_macos_auth_key.sh - do not edit by hand.
// The producer auth PUBLIC key (base64 of the raw X9.63 point). A public key is
// not a secret and is safe to keep in the repo; the matching PRIVATE key never
// enters the repo - it lives in the host app's login keychain, whose ACL
// securityd enforces against the host's live designated requirement at signing
// time (stage 6, W6-2 mode K).
static NSString* const kKMHostProducerPubKeyBase64 = @"BHos8AKyF8ujqvTTU5OPHrPvk9t4LdzrrsevRUK1tXgFQJ22rLEOa/XMBhZU84GMVzer4feIfZOBcLNwU65tYok=";
