#!/bin/sh
# Stage 6 (W6-2 mode K): provisions the producer authentication key pair.
#
# The PRIVATE key is created inside the sandboxed host app's login keychain on
# first run of --provision-auth-key (its ACL is the host's designated
# requirement, enforced by securityd against the live code signature at signing
# time). Only the PUBLIC key is exported here and written into
# macos/camera-extension/producer_auth_pubkey.h - no secret ever enters the
# repo or the logs. Re-running is idempotent (same key is re-exported); pass
# --rotate to generate a fresh key pair (extension must be rebuilt after that).
#
# Usage: sh scripts/provision_macos_auth_key.sh [host-binary] [--rotate]
set -e

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
HOST_BIN="${1:-$REPO_ROOT/macos/DerivedData/KMVirtualCamera/Build/Products/Debug/KMVirtualCamera.app/Contents/MacOS/KMVirtualCamera}"
ROTATE="$2"
HEADER="$REPO_ROOT/macos/camera-extension/producer_auth_pubkey.h"

if [ ! -x "$HOST_BIN" ]; then
    echo "host binary not found or not executable: $HOST_BIN" >&2
    echo "build first (xcodebuild ... build), then re-run this script" >&2
    exit 1
fi

if [ "$ROTATE" = "--rotate" ]; then
    PUB="$("$HOST_BIN" --provision-auth-key --rotate)"
else
    PUB="$("$HOST_BIN" --provision-auth-key)"
fi

# The app prints exactly one line: base64 of the raw X9.63 public point.
case "$PUB" in
    ""|*[!A-Za-z0-9+/=]*)
        echo "unexpected provision output (status in stderr above)" >&2
        exit 1
        ;;
esac

cat > "$HEADER" <<EOF
#pragma once
#import <Foundation/Foundation.h>
// GENERATED by scripts/provision_macos_auth_key.sh - do not edit by hand.
// The producer auth PUBLIC key (base64 of the raw X9.63 point). A public key is
// not a secret and is safe to keep in the repo; the matching PRIVATE key never
// enters the repo - it lives in the host app's login keychain, whose ACL
// securityd enforces against the host's live designated requirement at signing
// time (stage 6, W6-2 mode K).
static NSString* const kKMHostProducerPubKeyBase64 = @"$PUB";
EOF

echo "wrote $HEADER"
echo "public key bytes (decoded): $(( $(printf '%s' "$PUB" | wc -c) * 3 / 4 )) approx"
