include_guard(GLOBAL)
include(FetchContent)
# Configure dependency-local options in a function scope; do not turn our tests off.
function(km_prepare_opus)
    if(NOT KM_ENABLE_OPUS OR TARGET opus OR TARGET Opus::opus)
        return()
    endif()
    set(BUILD_TESTING OFF)
    set(BUILD_SHARED_LIBS OFF)
    set(OPUS_BUILD_SHARED_LIBRARY OFF)
    set(OPUS_BUILD_TESTING OFF)
    set(OPUS_BUILD_PROGRAMS OFF)
    set(OPUS_DRED OFF)
    set(OPUS_OSCE OFF)
    set(OPUS_HARDENING ON)
    FetchContent_Declare(km_opus
        URL https://downloads.xiph.org/releases/opus/opus-1.6.1.tar.gz
        URL_HASH SHA256=6ffcb593207be92584df15b32466ed64bbec99109f007c82205f0194572411a1)
    FetchContent_MakeAvailable(km_opus)
endfunction()
function(km_configure_audio target)
    target_compile_definitions(${target} PUBLIC KM_ENABLE_OPUS=$<BOOL:${KM_ENABLE_OPUS}>)
    if(KM_ENABLE_OPUS)
        km_prepare_opus()
        if(TARGET Opus::opus)
            target_link_libraries(${target} PUBLIC Opus::opus)
        else()
            target_link_libraries(${target} PUBLIC opus)
        endif()
    endif()
endfunction()
